### ISSUE TITLE
Top unbottled Linux formulae

### ISSUE THREAD

**Issue by danielnachun** [Homebrew/linuxbrew-core#22225]
As discussed on Slack, I've compiled a list of formulae which are not bottled on Linux.  It turns out there aren't that many unbottled Linux formulae with a non-relocatable cellar, so I'm just listing them here regardless of cellar.  The number next to the formula is the number of downloads in the last 365 days, and each sublist is ranked in descending order based on this.

I am submitting bottling jobs with `brew request-bottle`, and if they fail I'm updating this issue with what the current problem is.  This is basically how things are being done to track bottling issues for ARM and Big Sur in homebrew/core.  

EDIT: a lot of these are fixed now so I'm removing everything that's already checked off so it's easier to see what still needs to be fixed.

**Miscellaneous issues**
- [x] mysql (5062) linkage failure: `unexpected (metadata_cache.so)` - this is happening in `mysqlrouter_passwd`.  `metadata_cache.so` is in the `mysqlrouter` subdirectory of the `opt_lib`, which is not in the RPATH of `mysqlrouter_passwd`.  Perhaps the `LDFLAGS` have to be tweaked?
- [x] emacs (3228) bottling disabled in CI - need to check if this is a problem in Linux CI
- [x] bazel	(1106) https://github.com/Homebrew/linuxbrew-core/issues/21182 This will build with `--env=std`.  I think we need to patch the `compile.sh` script to add the Homebrew env vars with `--action_env`.  Also this needs `python` executable, but works with Python 3.
- [x] openshift-cli	(909) fails because of a conflict between `krb5` and `heimdal` (why are these both dependencies?). ~~Also uses `ENV.O0`.~~  Also uses `GOPATH`, which we are apparently trying to get rid of: https://github.com/Homebrew/homebrew-core/issues/47627
- [x] sratoolkit	(443) build failure: `chmod: cannot access 'libutf8proc.so.2.2.0': No such file or directory`
- [ ] mono (289) I've tried to build this before - mono itself build fine, but `msbuild` fails - the argument `/p:DisableNerdbankVersioning=true` made the build go farther but it still failed
- [ ] root (256) build failure for AFTERIMAGE - `ar: lib deps specified more than once` may be due to a recent change in `ar` arguments: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981072
- [ ] v8@3.15	(193) unversioned formula is **not** bottled - needs python as a dependency.  Also hard coded to look for `python` (this does work with Python 3 now).
- [ ] lanraragi	(192) cannot find headers for `libarchive` even though it is already included as a dependency - the install script seems to ignore the `CFLAGS` variable which is supposed to point to the location of `libarchive`
- [x] makensis	(149) https://github.com/Homebrew/linuxbrew-core/pull/22066
- [ ] unar	(139) https://github.com/Homebrew/linuxbrew-core/issues/14705 I've managed to build this on my system outside Homebrew because it was useful to me, it needs https://github.com/gnustep/libs-base as a dependency, which in turn needs `libobjc.so` which our GCC currently doesn't build.
- [ ] srecord	(128) needs `pstopdf` to build man pages - disable man page generation
- [ ] thrift@0.9	(128) unversioned formula is already bottled - audit failed: `* 0.9.3.1 is a GitHub pre-release.`
- [x] v8	(114) Everything is working for this now. ~~the only remaining issue is to stop it from using the bundled `zlib` and use the system one instead.~~ The bundled `zlib` is a fork with a different soname, so we should leave it alone.  Still wants a `python` executable like `v8@3.15`, but otherwise good to go!  
- [ ] opencv@3 (96) This will need a lot of work - I fixed the main `opencv` formula already, so it can be used as a template for this
- [ ] argp-standalone	(72) complex build failures.  Appears to be old and heavily patched.
- [ ] wakeonlan	(66) build failure: `Errno::ENOENT: No such file or directory - blib/man1/wakeonlan.1` - I think this is just missing the right prefix
- [ ] logstash	(65) ~~needs `ruby` as a dependency https://github.com/Homebrew/homebrew-core/pull/70601~~ now fails with multiple weird errors - needs a closer look
- [ ] bmake (65) fails a unit test - cause unclear.  The failing test is for `export` - perhaps it has a problem trying to set environment variables?
- [ ] docker-machine-driver-hyperkit	(62) build failure `package github.com/machine-drivers/docker-machine-driver-hyperkit: build constraints exclude all Go files in /tmp/docker-machine-driver-hyperkit-20210206-2761-416wtm/src/github.com/machine-drivers/docker-machine-driver-hyperkit`
- [ ] cmus (55) dependency `mad` seems to have a missing bottle - attempting to bottle `mad` again results in a test failure
- [ ] id3lib	(52) fails with `did you forget to '#include <cstring>'`
- [ ] ldid	(50) build failure: `fatal: unable to access 'https://git.saurik.com/ldid.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`.  This looks like it should be broken on macOS as well, and should be checked in `homebrew-core`.
- [ ] espeak (48) has a macOS-specific fix to the Makefile that needs to be in a `on_macos do` block 
- [ ] clamav (46) tries to uses `libiconv` which is not needed on Linux - dependency should be macOS-only
- [ ] haxe	(44) ocaml build failures - this needs to be looked at more carefully
- [ ] hyperscan	(43) build failure: `AVX2 support required to build fat runtime`
- [ ] wxpython	(43) ~~linkage failure: multiple libraries are missing - may also need `gtk3` as a dependency~~ This one is a bit of a mess.  Although it is python package, it build and installs some C libraries into the `site-packages` directory which need to be found by the linker.  I can fix this by just symlinking those into the `opt_lib` directory, but I'm not sure if this is acceptable.
- [x] gnumeric (43) build failure: `configure: error: XML::Parser perl module is required for intltool` 
- [ ] chronograf	(41) build failure: `Error: Can't find Python executable "/usr/bin/python", you can set the PYTHON env variable` 

**missing dependencies**
- [x] qemu (492) build failure: `../hw/usb/host-libusb.c:953:32: error: ‘USBDEVFS_GET_SPEED’ undeclared (first use in this function)` - this error occurs because it needs `linux-headers` from kernel 4.13 or greater, and our package is for kernel 4.4 https://patchwork.kernel.org/comment/23585989/ - alternatively we can disable `libusb` support, not sure if that is important.
- [ ] swift (426) ~~missing dependency `python` (probably needs other changes as well to build) I made substantial progress with this.  Lots of changes are needed but it seems close!~~ The latest release version still requires Python 2, but the development preview of 5.4 does not.  We can revisit this on Linux when 5.4 is released.
- [ ] podman	(265) ~~build script contains macOS-specific references, but the package also supports Linux.~~ It looks like this is missing several dependencies which are not currently available as formulae: https://github.com/Homebrew/linuxbrew-core/pull/22227.  A contributor has offered to try to add these dependencies.  
- [x] dotnet	(257) https://github.com/Homebrew/linuxbrew-core/issues/22063 I'm pretty sure this needs this version of libunwind: https://github.com/libunwind/libunwind, which needs a new formula
- [ ] portmidi	(239) Uses a macOS-specific makefile; missing `alsa` as a dependency
- [ ] neomutt (196) needs `libxslt` as a dependency - also has some `lua` build issue
- [x] opensc (129) needs `pcsc-lite` as a dependency
- [ ] sc-im (118) needs `yacc` as a dependency
- [ ] sfml	(113) missing `x11` - need to add `x11` as a dependency or disable it
- [ ] libvirt (96) requires `rpcgen` as dependency, which is macOS-only.  This dependency should only be required for macOS, and a suitable Linux replacement, if needed, should be added as a Linux dependency
- [ ] pypy	(95) needs `tcl` as a dependency 
- [ ] bmon	(94) missing dependency `libnl` ~~- hopefully this can be disabled, as we don't have a formula for it right now~~ `libnl` seem to be essential to the functioning of this on Linux, so we need to make a `libnl` formula  
- [ ] grafana	(89) needs `python` as a dependency on Linux 
- [ ] mu	(88) ~~unbottled dependency `emacs`~~ needs `m4` as a dependency
- [ ] sleuthkit	(79) needs `gnu-sed` as a dependency - adding `gnu-sed` as a dependency doesn't fix this
- [ ] urlview	(76) needs `librx` as a dependency, which we don't currently have a formula for.  We should see if this is optional and can be disabled
- [ ] ~~pdf2htmlex (75) this downloads an older version of `poppler` as a resource, but the comment for this is from 2017, and it should be tried again with the newest version `poppler` as a regular dependency~~ upstream repo says it is now unmaintained, should probably be disabled?  
- [ ] sqlcipher	(64) needs `sqlite` as dependency 
- [ ] semgrep	(61) needs `m4` as a dependency
- [x] volta	(60) ~~needs `pkg-config` as a dependency~~ and `openssl`
- [ ] dvc	(58) needs `libxml2` as a dependency - also has other more complex build failures
- [ ] swig@3 (58) needs `ruby` as a dependency in testing, not just build - it is already a test dependency, but still fails
- [ ] hping	(54) needs `libpcap` as a dependency - unmaintained and may need to be disabled
- [ ] allegro	(53) missing `x11` - need to add `x11` as a dependency.  The dependency `dumb` needs to be updated to build shared libs.  The test also fails.
- [x] thors-serializer	(49) needs dependency `python` - also has issues with gcc
- [ ] borgbackup	(48) missing dependency `libacl` which we don't have a formula for.  ACL support sounds like it might be important for this tool, so we may need to make a formula for `libacl`
- [ ] bulk_extractor (48) needs `flex` as a dependency - also fails because it cannot find the version of the boost library
- [ ] vapor	(47) needs `swift`, which is available on Linux.  But I don't think our `swift` formula supports Linux right now 
- [ ] mint	(46) needs `swift`, which is available on Linux.  But I don't think our `swift` formula supports Linux right now
- [ ] percol	(43) missing test dependency `expect` - it is already a test dependency, not sure why this is failing
- [x] handbrake (40) needs `m4` as a dependency - also need to disable NUMA - it also needed a whole bunch of other stuff but works now.  I'm still figuring out to reduce the number of dependencies I had to add.
- [ ] leela-zero (40) needs OpenCL as a dependency - not sure if we provide this on Linux

**needs newer gcc**
- [x] emscripten	(302) https://github.com/Homebrew/linuxbrew-core/issues/22198 This build fine with a newer `gcc`.  UPDATE: it installs pre-built binaries in with NPM.  This may just need to be disabled on Linux.
- [ ] folly	(215) probably needs a newer version of `gcc` - also has a problem with linking to boost
- [ ] libgccjit (68) ~~probably needs to be built with gcc@10 - also fails with `recipe for target 'stage1-bubble' failed`~~ https://github.com/Homebrew/linuxbrew-core/pull/23195
- [x] lc0	(53) needs gcc@8 or later https://github.com/Homebrew/linuxbrew-core/pull/22550
- [ ] graph-tool (51) needs at least `gcc@7` - also has an issue finding Python libraries

**needs to be marked macOS-only** https://github.com/Homebrew/homebrew-core/pull/70804
- [ ] vault	(510) unbottled dependencies `node@10` - `node@10` is macOS-only and about to be deprecated.  If this doesn't work with a newer version of node it will have to be deprecated as well.
- [ ] couchdb	(90) this needs `spidermonkey`, which only builds with `python2`.  Upstream has indicated a desire to move to a different JavaScript engine, but has not yet done so.

**test failures**
- [ ] node@14	(820) unversioned formula is already bottled - fails test for bufferutil.  Should check if test is different in unversioned formula
- [x] elasticsearch	(487) builds successfully but fails test `java.lang.RuntimeException: can not run elasticsearch as root`.   
- [ ] geckodriver	(402) ~~Builds successfully but fails test.  Needs an open port - I think we have other tests that check for an open port already.~~ actually fails because it needs `netcat` as a test dependency
- [ ] scrcpy (282) test failure: `CRITICAL: Could not initialize SDL: No available video device` - test probably needs to be disabled in headless CI
- [x] adios2 (205) test failure: `ModuleNotFoundError: No module named 'adios2'`
- [ ] vips (192) ~~unbottled dependency `libspng`~~ test failure: pngload: zlib init error
- [ ] postgis	(139) builds but fails test with `Error: postgis: failed`
- [ ] lsusb	(85) test failure: `/home/linuxbrew/.linuxbrew/Cellar/lsusb/1.0/bin/lsusb: line 7: system_profiler: command not found` - this is a cross platform tool, but `system_profiler` is a macOS-only command.  The test needs to be fixed to also work on Linux.
- [ ] zenith	(84) test failure: ` Errno::EIO: Input/output error @ io_fread - /dev/pts/0` -  test probably needs to be disabled in headless CI
- [ ] chart-testing	(83) test failure: `Error: Error loading configuration: 'lintconf.yaml' neither specified nor found in default locations`
- [ ] v2ray	(70) test failure: `/home/linuxbrew/.linuxbrew/Cellar/v2ray/4.34.0/bin/geoip.dat: no such file or directory`
- [ ] clojure-lsp	(56) ~~unbottled dependency `leiningen`~~ test failure: `cannot load such file -- Open3`
- [ ] fping	(55) test failure: `Test::Unit::AssertionFailedError: <"::1 is alive"> expected but was <"127.0.0.1 is alive">`
- [ ] stunnel	(53) test failure: `Test::Unit::AssertionFailedError: </successful/> was expected to be =~ <"">.`
- [ ] teleport	(53) test failure: `inreplace failed /tmp/teleport-test-20210206-15575-1kpvvnt/config.yml: expected replacement of "/usr/bin/hostname" with "/bin/hostname"`
- [ ] terraforming	(50) ~~needs `ruby` as a dependency~~ test failure: `'require': cannot load such file -- webrick/httputils (LoadError)`
- [ ] lmod	(47) ~~missing dependency `tcl-tk`.  Can be disabled by adding `--with-fastTCLInterp=no` to configure args.~~ test failure
- [ ] gping	(43) test failure: `Errno::EIO: Input/output error @ io_fread - /dev/pts/0` -  test probably needs to be disabled in headless CI
- [x] libsoup (41) test failure: ERROR:test.c:7:main: 'SOUP_STATUS_IS_SUCCESSFUL(msg->status_code)' should be TRUE`

**unbottled dependency**
- [x] tree-sitter	(340) unbottled dependency `emscripten`
- [ ] argo	(163) unbottled dependency `node@14`
- [ ] lammps (118) unbottled dependency `kim-api`
- [x] rtags	(92) unbottled dependency `emacs`
- [ ] pypy3 (86) unbottled dependency `pypy`
- [x] agda (63) unbottled dependency `emacs`
- [ ] gitversion	(55) unbottled dependency `dotnet` https://github.com/Homebrew/linuxbrew-core/issues/22063

**bad LDFLAGS**
- [ ] cabocha (147) formula adds extra `LDFLAGS` that only work on macOS - need to be put inside `on_macos do` block
- [ ] libmms	(125) formula adds extra `LDFLAGS` that only work on macOS - need to be put inside `on_macos do` block 
- [ ] minicam (85) formula adds extra `LDFLAGS` that only work on macOS - need to be put inside `on_macos do` block 

**shim references**
- [x] swi-prolog
- [ ] gnu-cobol
- [ ] gmt (56)

**package installs upstream binaries**
- [ ] texlive	(592) ~~builds successfully but fails linkage test because of X11 libraries (which are included as dependencies) - the superenv seems to be missing linker flags for all the dependencies~~ This formula currently downloads pre-built binaries.  It needs a complete redo, but fortunately Arch Linux has a good PKGBUILD to guide us: https://github.com/archlinux/svntogit-packages/blob/packages/texlive-bin/trunk/PKGBUILD
- [ ] serverless (413) linkage failiure: `unexpected (libpython3.7m.so.1.0)` - already has `python@3.9` as a dependency - this happens because there is a native add-on which wants python 3.7, which is keg only.  The offending file is a vendored file which has a Python fallback and should be deleted: https://github.com/Homebrew/discussions/discussions/870#discussioncomment-396040
- [x] gatsby-cli	(224) this is another `npm` package installing binaries   
- [ ] appium	(132) ~~missing dependences `glib`, `nspr`, `nss` and `libxcb` on Linux~~ This is the same issue as with `serverless` - a node package which downloads binaries that want to link to specific versions of libraries.  Update: disabling the chromedriver plugin fixes this - see https://github.com/Homebrew/discussions/discussions/870#discussioncomment-396040 for details.
- [ ] insect	(86) ~~unbottled dependency `pulp`~~ `npm` package installing binaries again

**disabled/already macOS-only**

**Comment by jonchang** [comment]
It'd probably be more straightforward to just directly use `brew request-bottle` instead since that can run on GitHub-hosted containers. Thanks for setting this up!

**Comment by danielnachun** [comment]
Awesome, I'll just start dispatching some of these bottle requests and document the failures.

**Comment by jonchang** [comment]
Hmm, I was unaware that ENV.O0 and friends are now disabled. We should have opened an issue in homebrew/core and created a rubocop autocorrector prior to its deprecation to ensure that no formulae depend on customizing optimization flags. As it stands right now all of those formulae will fail to build on macOS as well. Do you mind opening an issue in homebrew/core to get help on fixing these?

**Comment by danielnachun** [comment]
Yes, I was going to ask about that on Slack.  I'll go ahead and open an issue there since it sounds like this can be easily automated.

**Comment by carlocab** [comment]
I found a workaround for `ENV.O0` being disabled at https://github.com/Homebrew/homebrew-core/pull/70596.

It would be helpful to know why it was disabled in the first place so I can understand whether my workaround is the right thing to do.

**Comment by carlocab** [comment]
>tree-sitter (340) unbottled dependency `emscripten`

`tree-sitter` is actually a C library, so shouldn't have dependencies. `emscripten` is only for the bells and whistles. You can take it out for Linux. (I'm not against taking out completely too.)

**Comment by danielnachun** [comment]
> > tree-sitter (340) unbottled dependency `emscripten`
> 
> `tree-sitter` is actually a C library, so shouldn't have dependencies. `emscripten` is only for the bells and whistles. You can take it out for Linux. (I'm not against taking out completely too.)

Thanks @carlocab.  I think if nobody objects we should drop `emscripten` as a dependency for that on both platforms.  It's a huge behemoth to add and it seems from the documentation that the user can just install `emscripten` separately and it will still work.

**Comment by danielnachun** [comment]
@issyl0 Thank you for committing those, and please double check what I have written whenever possible - we have another ~1600 formulae to go and it's inevitable I will make mistakes.

Specifically regarding `telnet`, I think the reason Apple provides that download is because on Linux, `telnet` is provided as part of `inetutils`, so there is no standalone GNU `telnet` package.  Perhaps we should add a message for `telnet` to tell Linux users to install `inetutils` instead?

**Comment by issyl0** [comment]
@danielnachun This list is super useful, so thanks for putting it together. No problem on the contributions - it's good to get back into this side of things again.

Yeah, `telnet` is a formula that has consistently surprised me with it's not being buildable via Homebrew on Linux. I'm not sure we (currently) have a mechanism for `depends_on :macos` to have a reason associated with it to point people elsewhere if they're on Linux. We could use `disable!` on Linux with a message, but that feels pretty hacky. If anyone's got any other bright ideas, shout!

**Comment by danielnachun** [comment]
> I'm not sure we (currently) have a mechanism for `depends_on :macos` to have a reason associated with it to point people elsewhere if they're on Linux. We could use `disable!` on Linux with a message, but that feels pretty hacky, and I'm not sure off the top of my head what would take precedence - the `disable!` or if an install would fail the `depends_on :macos` requirement first. If anyone's got any other bright ideas, shout!

Although I don't consider this a high priority, it seems like it could be useful to have a way to explain to users why a formula is platform-specific and, when available, point them to equivalent formulae for their platform.  Little things like that can really improve the user experience, especially for beginners!

**Comment by carlocab** [comment]
I've gone ahead and made the annoying bits of tree-sitter Intel macOS only (`emscripten` is also broken on ARM), so you should be able to build a bottle for it now.

**Comment by danielnachun** [comment]
Actually, `emscripten` builds fine on Linux with a newer `gcc`.  So we don't have to remove `emscripten` as a dependency.

**Comment by carlocab** [comment]
Well, I wish I knew that earlier. 😅 I'll clean up the formula in homebrew/core and you can bottle it at the next merge.

**Comment by danielnachun** [comment]
Sorry again for not updating about that!  I'm waiting to fix `emscripten` until we've merged the PRs to harmonize `gcc` with homebrew/core, because we have a lot formula that need a newer GCC and I think we'll just be using `depends on "gcc"` from now on instead of specific `gcc` versions.

**Comment by carlocab** [comment]
No big deal, it's easy to fix: https://github.com/Homebrew/homebrew-core/pull/71291

**Comment by iMichka** [comment]
>  we'll just be using depends on "gcc" from now on instead of specific gcc versions.

You'll have to add `fails_with :gcc5` to make that work once my massive gcc PR has been merged. Because `depends on "gcc"` will mostly be a no-op on linux when used alone.

**Comment by dannydarvish** [comment]
Have you made any progress building mpich? I am currently attempting to `brew install mpich` on Ubuntu with the same failure.

**Comment by danielnachun** [comment]
> Have you made any progress building mpich? I am currently attempting to `brew install mpich` on Ubuntu with the same failure.

I updated the main post to explain the issue but in essence it is because the formula assumes we are building with gcc-10 but we are actually using gcc-5 on Linux.  When https://github.com/Homebrew/linuxbrew-core/pull/21380 is merged it will use gcc-10.  Building with gcc-10 currently doesn't work without some manual intervention either, because the gcc-10 formula only has the versioned `gfortran-10` but not `gfortran`.  We'll either have to add `gfortran` to our shim or create a `gfortran` symlink to `gfortran-10` for this to work correctly.

**Comment by sjackman** [comment]
> create a gfortran symlink to gfortran-10 for this to work correctly.

The formula `gcc` will provide an unversioned `gfortran` symlink to `gfortran-10` (unlike `gcc` and `g++`).

**Comment by danielnachun** [comment]
@dannydarvish `mpich` is now bottled.

**Comment by lexicol** [comment]
dnsperf PR: https://github.com/Homebrew/homebrew-core/pull/72629

**Comment by danielnachun** [comment]
I finally managed to finish testing all the other unbottled formulae I had in my list (about 1900 in total).  About 700 ended up bottling without needing any modifications, leaving about 1200 which need fixes.  I used a spreadsheet to document the failures which can be found here: https://docs.google.com/spreadsheets/d/1ydmVThL1McgBwbFT1wzLjuu2Y0yL_r2dL2JqvBVqoIs/edit?usp=sharing.  

Please let me know if you'd like edit access if you're interested in helping to fix some of these formulae.  I think the majority only need simple fixes like missing dependencies.  I don't necessarily expect us to have all of these fixed before we merge with homebrew-core, but hopefully we can fix the "low hanging fruit" relatively soon.

**Comment by sjackman** [comment]
> mysql (5062) linkage failure: unexpected (metadata_cache.so) - this is happening in mysqlrouter_passwd. metadata_cache.so is in the mysqlrouter subdirectory of the opt_lib, which is not in the RPATH of mysqlrouter_passwd. Perhaps the LDFLAGS have to be tweaked?

More likely, `metadata_cache.so` is a plugin that is loaded dynamically at run time by `dlopen` rather than at link time by `ld.so`. I don't yet know of a good way for the audit code to distinguish plugins from typical shared libraries. It may be impossible. We may need a way to explicitly add known plugins to an allow-list in the formula.

**Comment by danielnachun** [comment]
> > mysql (5062) linkage failure: unexpected (metadata_cache.so) - this is happening in mysqlrouter_passwd. metadata_cache.so is in the mysqlrouter subdirectory of the opt_lib, which is not in the RPATH of mysqlrouter_passwd. Perhaps the LDFLAGS have to be tweaked?
> 
> More likely, `metadata_cache.so` is a plugin that is loaded dynamically at run time by `dlopen` rather than at link time by `ld.so`. I don't yet know of a good way for the audit code to distinguish plugins from typical shared libraries. It may be impossible. We may need a way to explicitly add known plugins to an allow-list in the formula.

So something like `ignore_linkage: metadata_cache.so`?  Interestingly I don't think I've seen this failure in any other formulae yet, but we still have many which don't build so it could still show up elsewhere.

**Comment by iMichka** [comment]
It's called `ignore_missing_libraries` and we use it in openjdk.

**Comment by ax3l** [comment]
For the
>  adios2 (205) test failure: ModuleNotFoundError: No module named 'adios2'

It might be that I am hard-coding Python 3.9 in the Formula, because I don't know better :)

**Comment by carlocab** [comment]
> We can also try to add `-DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_INSTALL_LIBDIR=lib` in case the system that builds the packages now defaults to `lib64/` paths. Is there a build log we can look at?

`std_cmake_args` already sets `CMAKE_INSTALL_PREFIX` and `CMAKE_INSTALL_LIBDIR` to the right values.

https://rubydoc.brew.sh/Formula.html#std_cmake_args-instance_method

**Comment by ax3l** [comment]
Can we try to bottle `adios2` with the latest code update again?
(I tried to open an issue, but there seems to be no "bottle request" template for this repo.)

**Comment by danielnachun** [comment]
The bottle run for `adios2` failed, but I was able to fix the test locally.  I've opened a PR with the fix: https://github.com/Homebrew/linuxbrew-core/pull/23428.

**Comment by carlocab** [comment]
Any chance we could get `emscripten` and `tree-sitter` bottled? We've missed two version bumps for `emscripten` because `tree-sitter`'s WASM library doesn't build after the `emscripten` updates. (Homebrew/homebrew-core#78307, Homebrew/homebrew-core#79571)

I'd be less concerned about breaking compilation of `tree-sitter` when we don't have any users that need to build it from source. (Of course, this might also mean we can't build a future version bump of `tree-sitter`, but I suppose we can just disable the WASM library then.)

**Comment by mconfalonieri** [comment]
I am unsure if this is the right place to post this... I am trying to make my program `sadplay` available for Homebrew users through a tap. I used the workflows set up by brew, but it turns out that one of the libraries required, `libbinio`, does not have a bottle for linux, and this makes the jobs triggered by the PR fail.

https://github.com/mconfalonieri/homebrew-sadplay/pull/1/checks?check_run_id=2922379899

**Comment by danielnachun** [comment]
The holdup we need to fix for `emscripten` is that it installs an NPM package which downloads binaries which link to host libraries.  I cannot find a way to force it to rebuild the native binaries.  We may need to just disable the NPM installation step on Linux until we can figure that out.  I'll try to update my PR for that and see it I can get it to pass without the NPM package.

**Comment by KittenApps** [comment]
`V8` 9.2 has now full support for Python 3 🎉 .

However I've currently still problems building `gn` with homebrew on linux. If I remember correctly you already found a solution for that previously, but I can't find it anymore. But it's totally worth looking into getting linux support for `V8` again now.

**Comment by chrmoritz** [comment]
`V8` 9.2 now fully support Python 3. So it's worth looking into it again. 🎉 

I still have problems building `gn` currently on linux, but if I remember correctly there was already a solution for that here.

**Comment by danielnachun** [comment]
That is good to know.  I had a branch that was building but require some unacceptable hacks to get around the lack of full Python 3 support.  If this is now resolved, that means we can pursue bottling it on Linux finally.  

I also never finished porting over the code Arch Linux uses to make a `.pc` file for `pkg-config`, but this should be easy enough.

**Comment by iMichka** [comment]
Closing here. You might want to redo the list based on homebrew-core, but the next efforts in the 6 months will probably to be bottle more Linux stuff in homebrew-core anyway, so a bunch of these will be worked on.

**Comment by iMichka** [comment]
Thanks all for your hard work here! :)
